Apply suggestion and update Check Merge Readiness logic
Co-authored-by: Zhiwei Liang <121905282+zliang-akamai@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,17 +60,10 @@ jobs:
         run: make lint
 
       - name: Check Merge Readiness
-        if: github.event_name == 'pull_request'
+        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'do-not-merge')
         run: |
-          LABELS='${{ toJson(github.event.pull_request.labels.*.name) }}'
-
-          if echo "$LABELS" | grep -q "do-not-merge"; then
-            echo "This PR is labeled as 'do-not-merge' so please make sure it is ready."
-            exit 1
-          else
-            exit 0
-          fi
-
+          echo "::error::This PR is labeled 'do-not-merge'."
+          exit 1
   unit-tests-on-ubuntu:
     runs-on: ubuntu-latest
     strategy:
